version: '2'
services:
  ps4exploithost_service:
    image: romancin/ps4-exploit-host:latest
    container_name: ps4-exploit-host
    restart: always
    networks:
      qnetbridge_network:
        ipv4_address: 192.168.1.6

networks:
  qnetbridge_network:
    external:
      name: qnetbridge_network
